var lirikaLinks =
[
  ["lirika/lirika_pro_ejika.html"],
  ["lirika/lirika_pro_medvedja.html"],
  ["lirika/lirika_pro_ejika.html"],
  ["lirika/lirika_pro_medvedja.html"],
  ["lirika/lirika_pro_ejika.html"],
  ["lirika/lirika_pro_medvedja.html"],
  ["lirika/lirika_pro_ejika.html"],
  ["lirika/lirika_pro_medvedja.html"],
  ["lirika/lirika_pro_ejika.html"],
  ["lirika/lirika_pro_medvedja.html"],
  ["lirika/lirika_pro_ejika.html"],
  ["lirika/lirika_pro_medvedja.html"],
  ["lirika/lirika_pro_ejika.html"],
  ["lirika/lirika_pro_medvedja.html"],
  ["lirika/lirika_pro_ejika.html"],
  ["lirika/lirika_pro_medvedja.html"],
  ["lirika/lirika_pro_ejika.html"],
  ["lirika/lirika_pro_medvedja.html"],
  ["lirika/lirika_pro_ejika.html"],
  ["lirika/lirika_pro_medvedja.html"]
]

var dramaLinks =
[
  ["drama/drama_pro_ejika.html"],
  ["drama/drama_pro_medvedja.html"],
  ["drama/drama_pro_ejika.html"],
  ["drama/drama_pro_medvedja.html"],
  ["drama/drama_pro_ejika.html"],
  ["drama/drama_pro_medvedja.html"],
  ["drama/drama_pro_ejika.html"],
  ["drama/drama_pro_medvedja.html"],
  ["drama/drama_pro_ejika.html"],
  ["drama/drama_pro_medvedja.html"],
  ["drama/drama_pro_ejika.html"],
  ["drama/drama_pro_medvedja.html"],
  ["drama/drama_pro_ejika.html"],
  ["drama/drama_pro_medvedja.html"],
  ["drama/drama_pro_ejika.html"],
  ["drama/drama_pro_medvedja.html"],
  ["drama/drama_pro_ejika.html"],
  ["drama/drama_pro_medvedja.html"],
  ["drama/drama_pro_ejika.html"],
  ["drama/drama_pro_medvedja.html"]
]